name: "mango906/productive-box"
author: "mango906"
description: "Are you an early 🐤 or a night 🦉? Let's check out in gist"
branding:
  icon: "activity"
  color: "blue"
runs:
  using: "node12"
  main: "dist/index.js"
